name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - id: commit_id
      run: 
        echo "::set-output name=id::$(git rev-parse HEAD)"

    - name: Kubectl utility
      uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'create configmap commit-id --from-literal=id=${{ steps.commit_id.outputs.id }}'
