name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Kubectl utility
      uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: '"get namespace -w"'
