name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:    
  prepare:
    runs-on: ubuntu-latest
    steps:
    - id: commit_id
      name: get commit id
      run: 
        echo "::set-output name=id::$(git rev-parse HEAD)"
    - name: create configmap
      uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'create configmap commit_id -n test --from-literal=id=${{ steps.commit_id.outputs.id }}'
  run-job:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'create job myjob --image=busybox:latest -n test -- echo $FIRST_NAME'
      env:
        FIRST_NAME: Mona
        middle_name: The
    - uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'wait --for=condition=complete --timeout=1h job/myjob -n test'
  clean:
    runs-on: ubuntu-latest
    if: always()
    needs: run-job
    steps:
    - uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'delete job my-job -n test'
    - uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'delete configmap commit_id -n test'
