name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
  commitid:
    runs-on: ubuntu-latest
    steps:
    - id: commit_id
      run: 
        echo "::set-output name=id::$(git rev-parse HEAD)"
  configmap:
    runs-on: ubuntu-latest
    needs: commitid
    steps:
    - name: Kubectl utility
      uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'create configmap commit_id -n test --from-literal=id=${{ steps.commit_id.outputs.id }}'
  job:
    runs-on: ubuntu-latest
    needs: configmap
    steps:
    - uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'create job my-job --image=busybox:latest -n test'
  wait:
    runs-on: ubuntu-latest
    needs: job
    steps:
    - uses: nickgronow/kubectl@v1.17.4
      with:
        config_data: ${{ secrets.kube_config }}
        args: 'wait --for=condition=complete --timeout=1h job/myjob -n test'
