name: k3s

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          cat ~/.kube/config
          ls -lah ~/.kube/config
          cd ~/.kube/
          pwd
      - name: run job
        run: |
          SHA=7f1abb1b1b5c0912761364eadff8a842daa8247a
          ls -lah ~/.kube/config
          cat <<EOF>>pod.json
          {"apiVersion":"v1","kind":"Pod","metadata":{"name":"NAME","namespace":"test","labels":{"app":"test"}},"spec":{"restartPolicy":"Never","containers":[{"name":"test","image":"codingcorp-docker.pkg.coding.net/nocalhost/public/testcase:COMMITID","imagePullPolicy":"Always","env":[{"name":"COMMIT_ID","value":"COMMITID"}],"volumeMounts":[{"name":"kubeconfig","mountPath":"/root/.kube/config","subPath":"config"}]}],"volumes":[{"name":"kubeconfig","hostPath":{"path":"~/.kube/"}}]}}
          EOF
          sed -i "s/COMMITID/${SHA}/g" pod.json
          sed -i "s/NAME/${SHA}/g" pod.json
          cat pod.json
          kubectl create namespace test || true
          cat pod.json | kubectl create -f -
          sleep 20
          kubectl describe pods ${SHA} -n test
          kubectl get pods ${SHA} -n test -o yaml
          kubectl logs pods/${SHA} -n test -f || true
          kubectl get pods ${SHA} -n test | grep Completed
