name: k8s

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
      - name: Testing
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          cat ~/.kube/config
          ls -lah ~/.kube/config
          cd ~/.kube/
          pwd
      - name: run job
        run: |
          SHA=7f1abb1b1b5c0912761364eadff8a842daa8247a
          
          kubectl create namespace test || true
          kubectl config view --raw > config
          IMAGE=codingcorp-docker.pkg.coding.net/nocalhost/public/testcase:$SHA
          docker run -d -v /home/runner/.kube/config:/root/.kube/config -e COMMIT_ID=$SHA --network host --name $SHA $IMAGE
          docker logs $SHA -f
