name: k8s

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: git tag v1
        timeout-minutes: 60
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(echo $(git tag | tail -2))
          TAG="v0.3.8 v0.3.9"
          echo $TAG
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: Testing
        timeout-minutes: 60
        shell: bash
        run: |
          echo ${{ env.RELEASE_VERSION }}
          pwd
          cd cmd
          dir
          ./main.exe
          curl -L  https://github.com/nocalhost/nocalhost/releases/latest/download/NocalhostInstaller.exe -o nhctlinstall.exe
          dir
          pwd
          ./nhctlinstall.exe
          helm version
          kubectl version
