name: k8s

on:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: git tag v1
        timeout-minutes: 60
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(echo $(git tag | tail -2))
          echo $TAG
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}
          export v1="v0.0.1"
          export v2="v0.0.2"
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v1
      - name: Testing
        timeout-minutes: 60
        run: |          
          echo ${{ env.RELEASE_VERSION }}
          echo $v1
          echo $v2
