name: k8s

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: git tag v1
        timeout-minutes: 60
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(echo $(git tag | tail -2))
          echo $TAG
          TAG="v0.3.8 v0.3.9"
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v1
      - name: Testing
        timeout-minutes: 60
        shell: bash
        run: |
          SHA=e73bc95a8d231a1c88f275327d104043282bfd00
          echo ${{ env.RELEASE_VERSION }}
          echo ${{ secrets.kube_config }} | base64 -d >> config
          path="$(pwd)""/config"
          echo path
          export KUBECONFIG_PATH=$path
          cp config /root/.kube/config
          cd /root/.kube/config
          ls -lah
          pwd
          export TAG=${{ env.RELEASE_VERSION }}
          export COMMIT_ID=$SHA
          ./test
