name: k8s

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  workflow_run:
    workflows: [ "k3s" ]
    types: [ completed ]

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: git tag v1
        timeout-minutes: 60
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(echo $(git tag | tail -2))
          TAG="v0.3.8 v0.3.9"
          echo $TAG
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: Testing
        timeout-minutes: 60
        shell: bash
        run: |
          SHA=6af9f631a320396481bfb74242236054a9deb2e6
          echo ${{ env.RELEASE_VERSION }}
          curl -L  https://github.com/nocalhost/nocalhost/releases/latest/download/NocalhostInstaller.exe -o nhctlinstall.exe          
          dir
          pwd
          cd cmd
          ./main.exe
          echo $PATH
          ./nhctlinstall.exe
          helm version
          kubectl version
          
          kubectl create namespace test || true
          
          kubectl create namespace test || true
          IMAGE=codingcorp-docker.pkg.coding.net/nocalhost/public/testcase:$SHA
          docker run -d -v /home/runner/.kube/config:/root/.kube/config -e COMMIT_ID=$SHA --network host --name $SHA $IMAGE
          docker logs $SHA -f || true
          docker ps -a
          ID=$(docker inspect "$(docker ps -aq --filter name=$SHA)" --format='{{.State.ExitCode}}') && echo "$ID" | grep '^1$'
          
  mac:
    runs-on: macos-latest
    if: always()
    steps:
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: git tag v1
        timeout-minutes: 60
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(echo $(git tag | tail -2))
          TAG="v0.3.8 v0.3.9"
          echo $TAG
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@master
        timeout-minutes: 10
      - uses: debianmaster/actions-k3s@master
        with:
          version: v1.18.2-k3s1
      - name: Testing
        timeout-minutes: 60
        shell: bash
        run: |
          SHA=6af9f631a320396481bfb74242236054a9deb2e6
          echo ${{ env.RELEASE_VERSION }}
          kubectl create namespace test || true
          IMAGE=codingcorp-docker.pkg.coding.net/nocalhost/public/testcase:$SHA
          docker run -d -v /home/runner/.kube/config:/root/.kube/config -e COMMIT_ID=$SHA --network host --name $SHA $IMAGE
          docker logs $SHA -f || true
          docker ps -a
          ID=$(docker inspect "$(docker ps -aq --filter name=$SHA)" --format='{{.State.ExitCode}}') && echo "$ID" | grep '^1$'
          
