name: k8s

on:
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: git tag v1
        timeout-minutes: 60
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(echo $(git tag | tail -2))
          echo $TAG
          TAG="v0.3.9 v0.4.0-rc1\n"
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v1
      - name: Testing
        timeout-minutes: 60
        shell: bash
        run: |          
          echo ${{ env.RELEASE_VERSION }}
