name: Windows

on:
  push:
    branches: [ master ]
    tags: ["v*"]
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: tag
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(git tag | tail -2)
          echo $TAG
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v1
      - name: test
        run: |
          ls -lha
          export COMMIT_ID=530cd0719319ea31e509a810a2d4133e78756136
          ./test
