name: minikube

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
      - name: sleep
        run: sleep 20
      - name: Interact with the cluster
        run: |
          kubectl get nodes
          kubectl cluster-info
          kubectl get pods -A
      - name: sleep
        run: |
          sleep 60
          kubectl get nodes
          kubectl cluster-info
          kubectl get pods -A
      - name: sleep
        run: |
          sleep 60
          kubectl get nodes
          kubectl cluster-info
          kubectl get pods -A     
      - name: sleep
        run: |
          sleep 60
          kubectl get nodes
          kubectl cluster-info
          kubectl get pods -A
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
      - name: sleep
        run: sleep 20
      - name: Interact with the cluster
        run: |
          kubectl get nodes
          kubectl cluster-info
          kubectl get pods -A
      - name: sleep
        run: |
          sleep 60
          kubectl get nodes
          kubectl cluster-info
          kubectl get pods -A
      - name: sleep
        run: |
          sleep 60
          kubectl get nodes
          kubectl cluster-info
          kubectl get pods -A     
      - name: sleep
        run: |
          sleep 60
          kubectl get nodes
          kubectl cluster-info
          kubectl get pods -A
