name: minikube

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
      - name: Pull image api
        run: |
          curl -fL -u fengcaiwen@coding.net "https://codingcorp-generic.pkg.coding.net/nocalhost/nhctl/nhctl-linux-amd64?version=e3e6ba6d8a54169ec3a6813ce6c2e34d09eb6793" -o nhctl
          chmod +x nhctl
          kubectl create ns test
          ./nhctl install bookinfo -u https://github.com/nocalhost/bookinfo.git -r test-case  -t rawManifest  --resource-path manifest/templates -n test
          kubectl get nodes
      - name: Watch
        run: |
          sleep 10
          kubectl get pods -n test
          sleep 10
          kubectl get pods -n test
          sleep 10
          kubectl get pods -n test  | grep productpage | awk -F ' ' '{print$1}' | xargs kubectl describe pods -n test
          
          
