name: minikube

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master
      - name: Pull image api
        run: |
          docker pull codingcorp-docker.pkg.coding.net/nocalhost/public/nocalhost-api:v0.4.1-rc4
