name: Windows

on:
  push:
    branches: [ master ]
    tags: ["v*"]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@master
        timeout-minutes: 10
      - name: tag
        if: startsWith(github.ref, 'refs/tags/v')
        shell: bash
        run: |
          git fetch --prune --unshallow --tags
          TAG=$(git tag | tail -2)
          echo $TAG
          echo "RELEASE_VERSION=${TAG}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}
      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v1
      - name: test
        shell: bash
        run: |
          echo ${{ env.RELEASE_VERSION }}
